ALTER SESSION SET CONTAINER = FREEPDB1;
WHENEVER SQLERROR CONTINUE

CREATE TABLE SMARTINBOX.inbox_message (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmail_uid     VARCHAR2(128),
  sender        VARCHAR2(512),
  subject       VARCHAR2(1000),
  received_at   TIMESTAMP,
  body_text     CLOB,
  status        VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_inbox_gmail_uid UNIQUE (gmail_uid)
);

CREATE TABLE SMARTINBOX.attachment (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id      NUMBER NOT NULL REFERENCES SMARTINBOX.inbox_message(id),
  filename        VARCHAR2(512) NOT NULL,
  mime_type       VARCHAR2(256),
  stored_path     VARCHAR2(2000),
  is_pdf          NUMBER(1) DEFAULT 0 NOT NULL,
  processed_flag  NUMBER(1) DEFAULT 0 NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.processing_job (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER NOT NULL REFERENCES SMARTINBOX.inbox_message(id),
  status        VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  started_at    TIMESTAMP,
  finished_at   TIMESTAMP,
  duration_ms   NUMBER,
  error_text    CLOB,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.classification (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER NOT NULL REFERENCES SMARTINBOX.inbox_message(id),
  category      VARCHAR2(32) NOT NULL,
  confidence    NUMBER(5,4),
  reason        VARCHAR2(2000),
  source        VARCHAR2(32) DEFAULT 'AI' NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.extracted_field (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id      NUMBER NOT NULL REFERENCES SMARTINBOX.inbox_message(id),
  field_group     VARCHAR2(64) NOT NULL,
  field_name      VARCHAR2(128) NOT NULL,
  field_value     CLOB,
  confidence      NUMBER(5,4),
  source_type     VARCHAR2(16),
  attachment_id   NUMBER REFERENCES SMARTINBOX.attachment(id),
  page_no         NUMBER,
  quote_snippet   VARCHAR2(2000),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.pdf_analysis (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id       NUMBER NOT NULL REFERENCES SMARTINBOX.inbox_message(id),
  attachment_id    NUMBER NOT NULL REFERENCES SMARTINBOX.attachment(id),
  flavor           VARCHAR2(32),
  language         VARCHAR2(32),
  original_excerpt CLOB,
  english_text     CLOB,
  summary_text     CLOB,
  relevance_note   VARCHAR2(2000),
  ocr_confidence   NUMBER(5,4),
  duration_ms      NUMBER,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.table_extract (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pdf_analysis_id NUMBER NOT NULL REFERENCES SMARTINBOX.pdf_analysis(id),
  attachment_id   NUMBER NOT NULL REFERENCES SMARTINBOX.attachment(id),
  page_no         NUMBER,
  table_json      CLOB,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.image_flag (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pdf_analysis_id NUMBER NOT NULL REFERENCES SMARTINBOX.pdf_analysis(id),
  attachment_id   NUMBER NOT NULL REFERENCES SMARTINBOX.attachment(id),
  page_no         NUMBER,
  description     CLOB,
  needs_review    NUMBER(1) DEFAULT 1 NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.review_action (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER NOT NULL REFERENCES SMARTINBOX.inbox_message(id),
  action_type   VARCHAR2(32) NOT NULL,
  reviewer      VARCHAR2(128),
  reason        VARCHAR2(2000),
  old_payload   CLOB,
  new_payload   CLOB,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE SMARTINBOX.ai_audit_log (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER,
  job_id        NUMBER,
  event_type    VARCHAR2(64) NOT NULL,
  detail        CLOB,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE PROCEDURE SMARTINBOX.log_ai_event (
  p_message_id IN NUMBER,
  p_job_id     IN NUMBER,
  p_event      IN VARCHAR2,
  p_detail     IN CLOB
) AS
BEGIN
  INSERT INTO SMARTINBOX.ai_audit_log (message_id, job_id, event_type, detail)
  VALUES (p_message_id, p_job_id, p_event, p_detail);
END;
/

GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.inbox_message TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.attachment TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.processing_job TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.classification TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.extracted_field TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.pdf_analysis TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.table_extract TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.image_flag TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.review_action TO SMARTINBOX;
GRANT SELECT, INSERT, UPDATE, DELETE ON SMARTINBOX.ai_audit_log TO SMARTINBOX;
GRANT EXECUTE ON SMARTINBOX.log_ai_event TO SMARTINBOX;

BEGIN
  EXECUTE IMMEDIATE 'CREATE OR REPLACE SYNONYM SMARTINBOX.inbox_message FOR SMARTINBOX.inbox_message';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Public synonyms so APP_USER can query unqualified names
CREATE OR REPLACE PUBLIC SYNONYM inbox_message FOR SMARTINBOX.inbox_message;
CREATE OR REPLACE PUBLIC SYNONYM attachment FOR SMARTINBOX.attachment;
CREATE OR REPLACE PUBLIC SYNONYM processing_job FOR SMARTINBOX.processing_job;
CREATE OR REPLACE PUBLIC SYNONYM classification FOR SMARTINBOX.classification;
CREATE OR REPLACE PUBLIC SYNONYM extracted_field FOR SMARTINBOX.extracted_field;
CREATE OR REPLACE PUBLIC SYNONYM pdf_analysis FOR SMARTINBOX.pdf_analysis;
CREATE OR REPLACE PUBLIC SYNONYM table_extract FOR SMARTINBOX.table_extract;
CREATE OR REPLACE PUBLIC SYNONYM image_flag FOR SMARTINBOX.image_flag;
CREATE OR REPLACE PUBLIC SYNONYM review_action FOR SMARTINBOX.review_action;
CREATE OR REPLACE PUBLIC SYNONYM ai_audit_log FOR SMARTINBOX.ai_audit_log;
CREATE OR REPLACE PUBLIC SYNONYM log_ai_event FOR SMARTINBOX.log_ai_event;
