-- Executed as APP_USER SMARTINBOX (see 01-init.sh)
WHENEVER SQLERROR CONTINUE
CREATE TABLE inbox_message (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  gmail_uid     VARCHAR2(128),
  sender        VARCHAR2(512),
  subject       VARCHAR2(1000),
  received_at   TIMESTAMP,
  body_text     CLOB,
  status        VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_inbox_gmail_uid UNIQUE (gmail_uid)
);

CREATE TABLE attachment (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id      NUMBER NOT NULL REFERENCES inbox_message(id),
  filename        VARCHAR2(512) NOT NULL,
  mime_type       VARCHAR2(256),
  stored_path     VARCHAR2(2000),
  is_pdf          NUMBER(1) DEFAULT 0 NOT NULL,
  processed_flag  NUMBER(1) DEFAULT 0 NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE processing_job (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER NOT NULL REFERENCES inbox_message(id),
  status        VARCHAR2(32) DEFAULT 'PENDING' NOT NULL,
  started_at    TIMESTAMP,
  finished_at   TIMESTAMP,
  duration_ms   NUMBER,
  error_text    CLOB,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE classification (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER NOT NULL REFERENCES inbox_message(id),
  category      VARCHAR2(32) NOT NULL,
  confidence    NUMBER(5,4),
  reason        VARCHAR2(2000),
  source        VARCHAR2(32) DEFAULT 'AI' NOT NULL,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE extracted_field (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id      NUMBER NOT NULL REFERENCES inbox_message(id),
  field_group     VARCHAR2(64) NOT NULL,
  field_name      VARCHAR2(128) NOT NULL,
  field_value     CLOB,
  confidence      NUMBER(5,4),
  source_type     VARCHAR2(16),
  attachment_id   NUMBER REFERENCES attachment(id),
  page_no         NUMBER,
  quote_snippet   VARCHAR2(2000),
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE pdf_analysis (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id       NUMBER NOT NULL REFERENCES inbox_message(id),
  attachment_id    NUMBER NOT NULL REFERENCES attachment(id),
  flavor           VARCHAR2(32),
  language         VARCHAR2(32),
  original_excerpt CLOB,
  english_text     CLOB,
  summary_text     CLOB,
  relevance_note   VARCHAR2(2000),
  ocr_confidence   NUMBER(5,4),
  duration_ms      NUMBER,
  created_at       TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE table_extract (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pdf_analysis_id NUMBER NOT NULL REFERENCES pdf_analysis(id),
  attachment_id   NUMBER NOT NULL REFERENCES attachment(id),
  page_no         NUMBER,
  table_json      CLOB,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE image_flag (
  id              NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pdf_analysis_id NUMBER NOT NULL REFERENCES pdf_analysis(id),
  attachment_id   NUMBER NOT NULL REFERENCES attachment(id),
  page_no         NUMBER,
  description     CLOB,
  needs_review    NUMBER(1) DEFAULT 1 NOT NULL,
  created_at      TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE review_action (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER NOT NULL REFERENCES inbox_message(id),
  action_type   VARCHAR2(32) NOT NULL,
  reviewer      VARCHAR2(128),
  reason        VARCHAR2(2000),
  old_payload   CLOB,
  new_payload   CLOB,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE TABLE ai_audit_log (
  id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id    NUMBER,
  job_id        NUMBER,
  event_type    VARCHAR2(64) NOT NULL,
  detail        CLOB,
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE OR REPLACE PROCEDURE log_ai_event (
  p_message_id IN NUMBER,
  p_job_id     IN NUMBER,
  p_event      IN VARCHAR2,
  p_detail     IN CLOB
) AS
BEGIN
  INSERT INTO ai_audit_log (message_id, job_id, event_type, detail)
  VALUES (p_message_id, p_job_id, p_event, p_detail);
END;
/
EXIT;

